blog/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'hot/$', views.HotView.as_view(), name='hot'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout,  {'next_page': '/'}, name='logout'),

    url(r'^author/(?P<pk>[0-9]+)/$', views.AuthorView.as_view(), name='author-detail'),
    url(r'^author/update$', views.AuthorUpdate.as_view(), name='author-update'),
    url(r'^author/posts/$', views.AuthorPostList.as_view(), name='author-posts'),

    url(r'post/add/$', views.PostCreate.as_view(), name='post-create'),
    url(r'post/(?P<pk>[0-9]+)/update/$', views.PostUpdate.as_view(), name='post-update'),
    url(r'post/(?P<pk>[0-9]+)/delete/$', views.PostDelete.as_view(), name='post-delete'),
    url(r'post/(?P<pk>[0-9]+)/like/$', views.PostLike.as_view(), name='post-like'),
    url(r'post/(?P<pk>[0-9]+)/comment/$', views.PostComment.as_view(), name='post-comment'),

    url(r'category/(?P<slug>[\w]+)/$', views.CategoryList.as_view(), name='category-list'),
    url(r'process-backlink', views.process_backlink, name='process-backlink'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),

]

if (settings.DEBUG):
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.urlresolvers import reverse
# Create your models here.


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    handle = models.CharField(max_length=200)
    rating = models.IntegerField(default=0)
    image = models.ImageField(upload_to='author/', default='author/no-img.jpg')

    @receiver(post_save, sender=User)
    def create_author(sender, instance, created, **kwargs):
        if created:
            Author.objects.create(user=instance, handle=instance.username)

    @receiver(post_save, sender=User)
    def save_author(sender, instance, **kwargs):
        instance.author.save()

    def __str__(self):
        return self.handle


class Category(models.Model):
    name = models.CharField(max_length=200)
    url = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    STATUS = ((0, 'draft'), (1, 'published'))
    DRAFT = 0
    PUBLISHED = 1

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=2000)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    url = models.CharField(max_length=50, unique=True)
    image = models.ImageField(upload_to='post', default='post/no-img.jpg')
    status = models.IntegerField(choices=STATUS, default=DRAFT)
    rating = models.IntegerField(default=0)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.text


class Request(models.Model):
    text = models.TextField('Request Text')
    created_at = models.DateTimeField(auto_now_add=True)

blog/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Author, Comment


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class UserUpdateForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email']

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['handle', 'image']

blog/views.py
from django.shortcuts import render, redirect
from django.views import generic, View
from django.views.generic.edit import FormView
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse

from .forms import UserForm, AuthorForm, UserUpdateForm
from .models import Post, Comment, Category, Author, Request


# Create your views here.

class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        return Post.objects.filter(status=Post.PUBLISHED)


class HotView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        return Post.objects.filter(status=Post.PUBLISHED).order_by('-rating')


class DetailView(generic.DetailView):
    model = Post
    template_name = 'blog/detail.html'


class PostCreate(generic.CreateView):
    login_required = True
    model = Post
    fields = ['title', 'text', 'url', 'image', 'status', 'category']

    def form_valid(self, form):
        obj = form.save(commit=False)
        if self.request.user.is_authenticated():
            obj.user = self.request.user
            obj.publish()
            return super(PostCreate, self).form_valid(form)
        else:
            return redirect('blog:login')


class PostUpdate(generic.UpdateView):
    login_required = True
    model = Post
    fields = ['title', 'text', 'url', 'image', 'status', 'category']

    def form_valid(self, form):
        obj = form.save(commit=False)
        if self.request.user == obj.user:
            obj.publish()
            return super(PostUpdate, self).form_valid(form)
        else:
            return redirect('blog:login')


class PostDelete(generic.DeleteView):
    login_required = True
    model = Post
    success_url = reverse_lazy('blog:index')

    def delete(self, *args, **kwargs):
        if self.request.user is self.model.user:
            raise Exception(self.model.user)
        return super(PostDelete, self).delete(*args, **kwargs)


class PostLike(View):
    login_required = True

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            post = Post.objects.get(pk=self.kwargs.get('pk'))
            post.rating = post.rating + 1
            post.user.author.rating = post.user.author.rating + 1
            post.user.author.save()
            post.save()
            return redirect(request.META.get('HTTP_REFERER'))
        else:
            return redirect('blog:login')


class PostComment(View):
    login_required = True

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            comment = Comment()
            comment.text = request.POST['text']
            comment.user = request.user
            comment.post = Post.objects.get(pk=self.kwargs.get('pk'))
            comment.publish()
            return redirect(request.META.get('HTTP_REFERER'))
        else:
            return redirect('blog:login')


class UserFormView(View):
    form_class = UserForm
    template_name = 'blog/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('blog:index')

        return render(request, self.template_name, {'form': form})


class AuthorView(DetailView):
    model = User
    template_name = 'author/detail.html'


class AuthorUpdate(View):
    template_name = 'author/update_form.html'
    login_required = True

    def get(self, request):
        user_form = UserUpdateForm(instance=request.user)
        author_form = AuthorForm(instance=request.user.author)
        return render(request, self.template_name, {
            'user_form': user_form,
            'author_form': author_form
        })

    def post(self, request):
        user_form = UserUpdateForm(request.POST, instance=request.user)
        author_form = AuthorForm(request.POST, request.FILES, instance=request.user.author)

        if user_form.is_valid() and author_form.is_valid():
            user_form.save()
            author_form.save()

        return redirect('blog:author-detail', request.user.pk)


class AuthorPostList(generic.ListView):
    template_name = 'blog/post-list.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        return Post.objects.filter(user=self.request.user)


class CategoryList(generic.DetailView):
    model = Category
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    slug_field = 'url'

    def get_object(self, queryset='url'):
        object = super(CategoryList, self).get_object()
        return object.post_set.all


@csrf_exempt
def process_backlink(request):
    if request.POST is not None:
        Request.objects.create(text=request.POST)
    return HttpResponse('1', content_type='text/plain')

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Блог{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="{% static 'blog/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'blog:index' %}">Блог</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class=""><a href="{% url 'blog:index' %}"><span class="glyphicon glyphicon-book" aria-hidden="true"></span>Посты</a></li>
                <li class=""><a href="{% url 'blog:hot' %}"><span class="glyphicon glyphicon-star" aria-hidden="true"></span>Топ</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'blog:post-create' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Добавить пост
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'blog:author-posts' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>Мои посты
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'blog:author-update' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>Профиль
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'blog:logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>Выйти
                        </a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'blog:login' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>Войти
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'blog:register' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>Регистрация
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}

<footer class="footer" style="margin-top: 30px;">
    <div class="container">
    <hr>
        <div class="text-center center-block">
            <p class="txt-railway">Django Blog</p>
            <br/>
                <a href="https://www.facebook.com/rjlth"><i class="fa fa-facebook-square fa-3x social"></i></a>
	            <a href="https://bitbucket.org/rjlth/"><i class="fa fa-bitbucket-square fa-3x social"></i></a>
	            <a href="mailto:zhandos.kapezov@gmail.com"><i class="fa fa-envelope-square fa-3x social"></i></a>
        </div>
    <hr>
</div>
</footer>
</body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% block body %}
    <div class="container">
        <div class="col-sm-12">
            <h1>{{ post.title }}</h1>
            <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-responsive">
            <p>{{ post.text }}</p>
            <p>rating: {{ post.rating }}</p>
        </div>
        
        <div class="col-sm-12">
            <form action="{% url 'blog:post-comment' post.id %}" class="form form-horizontal" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="col-sm-12">
                        <textarea name="text" rows="10" style="width: 100%"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-12">
                        <button type="submit" class="btn btn-success">Оставить коментарий</button>
                    </div>
                </div>
            </form>
        </div>

        <div class="col-sm-12">
            <div class="row">
                {% for comment in post.comment_set.all %}
                <ul class="media-list">
                    <li class="media">
                        <a class="media-left" href="{% url 'blog:author-detail' comment.user.id %}">
                            <img src="{{ comment.user.author.image.url }}" alt="{{ comment.user.author.handle }}" style="height: 100px;">
                            <p class="text-center">{{ comment.user.author.handle }}</p>
                        </a>
                        <div class="media-body">
                            {{ comment.text }}
                        </div>
                    </li>
                </ul>
                {% endfor %}
            </div>
        </div>
    </div>
    
    
{% endblock %}

blog/templates/blog/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class=" col-sm-12">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label" for="post_title">{{ field.label_tag }}</label>
        <div class="col-sm-12">{{ field }}</div>
    </div>
{% endfor %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block body %}
    <div class="container">
    {% if post_list %}
        {% for post in post_list %}
            {% if not forloop.counter|divisibleby:"2" %}
                <div class="row">
            {% endif %}
            <div class="col-sm-6" style="margin-top: 20px;">
                <div style="border: 1px solid black; border-radius: 2px;">
                    <p>published at: {{ post.published_date }}</p>
                    <p>published by <a href="{% url 'blog:author-detail' post.user.id %}">{{ post.user.author.handle }}</a></p>
                    <h2><a href="{%  url 'blog:detail' post.id %}">{{ post.title }}</a></h2>
                    <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-responsive">
                    <p class="post-rating">rating: {{ post.rating }}</p>
                    <p>
                        Категория:
                        <a href="{% url 'blog:category-list' post.category.url %}">{{ post.category.name }}</a>
                    </p>
                    <a class="post-like" href="{% url 'blog:post-like' post.id %}">Нравится</a>
                </div>
            </div>
            {% if forloop.counter|divisibleby:"2" or forloop.last %}
                </div>
            {% endif %}
        {% endfor %}
    {% else %}
        <p>There is no posts</p>
    {% endif %}
    </div>
{% endblock %}

blog/templates/blog/post-list.html
{% extends 'blog/base.html' %}

{% block body %}
    <div class="container">
    {% if post_list %}
        <div class="row">
        {% for post in post_list %}

            <div class="col-sm-12">
                <p>published: {{ post.published_date }}</p>
                <h2><a href="{%  url 'blog:detail' post.id %}">{{ post.title }}</a></h2>
                <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-responsive">
                <p class="post-rating">rating: {{ post.rating }}</p>
                <a href="{% url 'blog:post-update' post.id %}" class="btn btn-success" >Изменить</a>
                <form action="{% url 'blog:post-delete' post.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-danger">Удалить</button>
                </form>
            </div>

        {% endfor %}
        </div>
    {% else %}
        <p>У вас нет постов</p>
    {% endif %}
    </div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% block title %} Добавить пост {% endblock %}

{% block body %}
    <div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-10">
            <form class="form-horizontal" action="" enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {% include 'blog/form_template.html' %}
                <div class="form-group">
                    <div class="col-sm-12">
                        <button type="submit" class="btn btn-success">Добавить</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    </div>

{% endblock %}

blog/templates/blog/registration_form.html
{% extends 'blog/base.html' %}
{% block title %} Регистрация {% endblock %}

{% block body %}
    <div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-10">
            <form class="form-horizontal" action="" enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {% include 'blog/form_template.html' %}
                <div class="form-group">
                    <div class="col-sm-12">
                        <button type="submit" class="btn btn-success">Добавить</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    </div>

{% endblock %}